'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const CanonicalAsteraEngine = require('../src/canonical-astera-engine');
const { analyzeRequest, deriveEvidenceNeed, normalizeEvidencePacket } = require('../src/judgment-materials-analyzer');
const { routeDomainTemplates } = require('../src/domain-template-router');
const { QUERY_ROLES, buildCanonicalTaskPlan, evaluateCanonicalTaskPlan } = require('../src/canonical-claim-runtime');
const { projectCanonicalTask } = require('../src/canonical-task-projection');

const { createMockJapaneseParserClient } = require('./helpers/japanese-parser-mcp-mock');

const silentLogger={write(){}};
const tenant={id:'test',is_global:true,plan:'admin'};

function evidenceCandidate({id,role,family,authority,claim,url}){return{candidate_id:id,canonical_record_id:`${id}-record`,content_hash:`${id}-hash`,source_role:role,source_family_id:family,source_id:`${id}-source`,provider_id:`${id}-provider`,authority_id:authority,canonical_locator:{url,replayable:true},updated_at:'2026-08-20T00:00:00.000Z',fields:{claim},excerpt:claim};}
function queryExecution(queries=[]){return{initial:queries.map((query)=>({query_id:query.query_id,claim_id:query.claim_id,role:query.role,status:'FOUND',provider_records:[{provider_id:'ev-official-provider',status:'FOUND',candidate_record_ids:['ev-official-record']},{provider_id:'ev-corroboration-provider',status:'FOUND',candidate_record_ids:['ev-corroboration-record']}]})),reinforcement:[]};}
function validEvidence(claim,queries=[]){return{schema_version:'astera.evidence-search.result.v1',request_id:'ev-test',tenant_id:'test',status:'FINAL_VALID',effective_as_of:'2026-08-20T00:00:00.000Z',result_hash:'test-result-hash',planning_authority:'UPSTREAM_CANONICAL',planned_query_roles:Object.values(QUERY_ROLES),evidence:[evidenceCandidate({id:'ev-official',role:'OFFICIAL',family:'official-family',authority:'official-authority',claim,url:'https://official.test/evidence'}),evidenceCandidate({id:'ev-corroboration',role:'SECONDARY',family:'corroboration-family',authority:'corroboration-authority',claim,url:'https://corroboration.test/evidence'})],coverage:{discovery_scope_state:'COMPLETE_FOR_QUERY_SCOPE',registry_coverage_state:'COMPLETE_FOR_ACTIVE_REGISTRY'},quality:{initial:{status:'REINFORCEMENT_REQUIRED',phase:'INITIAL',score_bp:8500,gates:{initial_minimum_bp:8000,final_minimum_bp:9500},blocking_reasons:[]},reinforcement_attempt_count:1,new_corroboration_count:1,final:{status:'FINAL_VALID',phase:'FINAL',score_bp:9700,gates:{initial_minimum_bp:8000,final_minimum_bp:9500},blocking_reasons:[]}},query_execution:queryExecution(queries),provider_execution:{initial:[{provider_id:'ev-official-provider',status:'FULFILLED'}],reinforcement:[{provider_id:'ev-corroboration-provider',status:'FULFILLED'}]},ai_used:false,payment_executed:false};}
async function withEngine(fn){const engine=new CanonicalAsteraEngine({poolSize:2,logger:silentLogger,japaneseParserClient:createMockJapaneseParserClient()});try{await fn(engine);}finally{await engine.destroy();}}
function assertMaterialTextOmitsFixedEnvelope(materialText){assert.doesNotMatch(materialText,/^判断材料$/m);assert.doesNotMatch(materialText,/^Judgment Material$/m);assert.doesNotMatch(materialText,/導出根拠/);assert.doesNotMatch(materialText,/Derivation Basis/);assert.doesNotMatch(materialText,/External Consumerへ渡す内容/);assert.doesNotMatch(materialText,/Material for External Consumer/);assert.doesNotMatch(materialText,/^- rules=/m);assert.doesNotMatch(materialText,/^- tasks=/m);assert.doesNotMatch(materialText,/^- lenses=/m);assert.doesNotMatch(materialText,/^- evidence_refs=\d/m);assert.doesNotMatch(materialText,/^- blockers=/m);assert.doesNotMatch(materialText,/^- derivation=/m);}
async function planForPrepared(engine,claim){const prepared=await engine.prepareRequest({question:claim}),task=prepared.analysis_task_packet.tasks[0],plan=buildCanonicalTaskPlan(task,{primary:{id:'G01'}});return{prepared,plan};}

test('Japanese builtin analyzer path is disabled in favor of MCP authority',()=>{assert.throws(()=>analyzeRequest({question:'READMEは残す。APIを改善する。'}),(error)=>error.code==='JAPANESE_BUILTIN_ANALYZER_DISABLED');});

test('Japanese prepareRequest uses MCP projection instead of builtin decomposition',async()=>{await withEngine(async(engine)=>{const prepared=await engine.prepareRequest({question:'APIを改善する。'});assert.equal(prepared.instruction_understanding.parser,'Deterministic-Japanese-Parser-MCP');assert.ok(prepared.analysis_task_packet.tasks.length>=1);assert.equal(prepared.instruction_understanding.mode,'DEEP_PATH');});});

test('internal test verification does not force external Evidence Search while external verification does', () => {
  const request = analyzeRequest({ question: 'Verify the current API specification with official evidence.' });
  const external = request.analysis_task_packet.tasks[0];
  const internal = {
    ...external,
    id: 'T02',
    raw_text: 'Confirm behavior with internal tests only.',
    source_span: { start: 0, end: 42, text: 'Confirm behavior with internal tests only.' },
    verification: ['internal tests'],
    evidence_need: { required: false, reasons: [], queries: [] }
  };
  assert.equal(deriveEvidenceNeed(external, routeDomainTemplates({ question: external.source_span.text })).required, true);
  assert.equal(deriveEvidenceNeed(internal, routeDomainTemplates({ question: internal.source_span.text })).required, false);
});

test('Evidence FINAL_VALID compact packet still requires 80/95, reinforcement, corroboration, hash and non-AI contracts',()=>{const valid=normalizeEvidencePacket(validEvidence('API compatibility is preserved'));assert.equal(valid.state,'VALID');assert.equal(valid.initial_quality_score_bp,8500);assert.equal(valid.quality_score_bp,9700);assert.equal(valid.reinforcement_attempt_count,1);assert.equal(valid.new_corroboration_count,1);assert.equal(valid.distinct_authority_count,2);assert.equal(valid.distinct_source_family_count,2);const broken=validEvidence('API compatibility is preserved');broken.quality.reinforcement_attempt_count=0;broken.provider_execution.reinforcement=[];const rejected=normalizeEvidencePacket(broken);assert.equal(rejected.state,'REJECTED');assert.ok(rejected.eligibility_reasons.includes('REINFORCEMENT_COUNT_INVALID'));assert.ok(rejected.eligibility_reasons.includes('REINFORCEMENT_EXECUTION_MISSING'));});

test('canonical non-AI runtime builds Task Graph before Claim/Domain and all Main8 sections carry traces',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'READMEは残す。APIを改善する。成功条件は互換性維持とRollback可能であること。mainは変更するな。'},tenant);assert.equal(out.result.non_ai,true);assert.equal(out.runtime.ai_used,false);assert.equal(out.runtime.llm_called,false);assert.equal(out.runtime.engine,'v8_canonical_global_rules');assert.equal(Object.hasOwn(out,'answer'),false);assert.ok(out.result.analysis_task_packet.tasks.length>=2);assert.deepEqual(out.result.five_stage.order,['fact','risk','multi','inquiry','compare']);assert.equal(out.result.judgment.order.length,8);assert.equal(out.result.judgment.order[6],'07_evidence_status');for(const key of out.result.judgment.order){const section=out.result.judgment[key];assert.ok(section.decision_basis);assert.ok(section.decision_basis.rule_ids.length>=1);assert.equal(section.decision_basis.task_ids.length,out.result.analysis_task_packet.tasks.length);assert.ok(Array.isArray(section.decision_basis.source_spans));}assertMaterialTextOmitsFixedEnvelope(out.material.text);});});

test('material.text omits fixed derivation envelope while judgment retains decision_basis traces',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'READMEは残す。APIを改善する。成功条件は互換性維持とRollback可能であること。'},tenant);assertMaterialTextOmitsFixedEnvelope(out.material.text);assert.equal(out.result.judgment.order.length,8);for(const key of out.result.judgment.order){assert.ok(out.result.judgment[key].decision_basis?.rule_ids?.length>=1,`${key} missing decision_basis.rule_ids`);}});});

test('input claims are never promoted merely by wording, numbers, or product names',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'Node.js 22は本番で完全対応している。'},tenant);assert.equal(out.result.facts.confirmed.length,0);assert.ok(out.result.facts.unconfirmed.length>=1);assert.equal(out.result.canonical_claims.status,'UNDETERMINED');});});

test('evaluateCanonicalTaskPlan with strict G1-G7 evidence CONFIRMS matching claim internally',async()=>{await withEngine(async(engine)=>{const claim='Node.js 22は本番で対応している。',{prepared,plan}=await planForPrepared(engine,claim),task={...prepared.analysis_task_packet.tasks[0],canonical_plan:plan},projected=projectCanonicalTask({task,evidenceRaw:validEvidence(claim,plan.search_plan.queries)});assert.ok(projected.canonical.confirmed_count>=1);assert.equal(projected.canonical.undetermined_count,0);const evaluated=evaluateCanonicalTaskPlan(plan,validEvidence(claim,plan.search_plan.queries));assert.equal(evaluated.confirmed_count,projected.canonical.confirmed_count);});});

test('public process ignores client evidencePacket and keeps claims UNDETERMINED',async()=>{await withEngine(async(engine)=>{const claim='Node.js 22は本番で対応している。',{prepared,plan}=await planForPrepared(engine,claim),out=await engine.process({question:claim,evidencePacket:validEvidence(claim,plan.search_plan.queries),preparedRequest:prepared},tenant);assert.equal(out.result.facts.confirmed.length,0);assert.equal(out.result.canonical_claims.status,'UNDETERMINED');});});

test('rejected evidence never becomes CONFIRMED and no recommendation is produced',async()=>{await withEngine(async(engine)=>{const claim='Node.js 22は本番で対応している。',{prepared,plan}=await planForPrepared(engine,claim),packet=validEvidence(claim,plan.search_plan.queries);packet.status='REJECTED_BLOCKING';packet.quality.final={status:'REJECTED_BLOCKING',phase:'FINAL',score_bp:4200,gates:{initial_minimum_bp:8000,final_minimum_bp:9500},blocking_reasons:['SOURCE_CONFLICT']};const task={...prepared.analysis_task_packet.tasks[0],canonical_plan:plan},projected=projectCanonicalTask({task,evidenceRaw:packet});assert.equal(projected.canonical.confirmed_count,0);assert.ok(projected.canonical.undetermined_count>=1);const out=await engine.process({question:claim,evidencePacket:packet,preparedRequest:prepared},tenant);assert.equal(out.result.facts.confirmed.length,0);assert.equal(out.result.canonical_claims.status,'UNDETERMINED');assert.equal(out.result.comparison.verdict.decision,'MATERIAL_ONLY');assert.equal(out.result.comparison.selected_candidate,null);assert.deepEqual(out.result.comparison.candidate_ranking,[]);});});

test('Perspective Expansion never owns candidates, final scores, selection or rejection',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'旧Codeを分析し、根拠検索と責務分離を維持したままAstera本体を改善する。成功条件は非AIを維持し、未確認を事実化しないこと。'},tenant);assert.equal(out.result.perspective_expansion.mode,'MATERIAL_ONLY');assert.deepEqual(out.result.perspective_expansion.candidates,[]);assert.equal(out.result.perspective_expansion.selected,null);assert.deepEqual(out.result.perspective_expansion.rejected,[]);assert.equal(out.result.comparison.material_only,true);assert.equal(Object.hasOwn(out.result.comparison,'score'),false);});});

test('Task-specific Lens routing is retained per Analysis Task without forcing low-signal classification',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'APIサーバーのシステム開発を改善する。契約条件を確認する。'},tenant);const routes=out.result.judgment.lens_routing.per_task,tasks=out.result.analysis_task_packet.tasks;assert.equal(Object.keys(routes).length,tasks.length);assert.equal(routes[tasks[0].id].primary?.id,'G29');assert.equal(routes[tasks[1].id].primary,null);assert.equal(routes[tasks[1].id].classification_basis,'ABSTAIN_LOW_SIGNAL');});});

test('same compound input remains deterministic across repeated executions',async()=>{await withEngine(async(engine)=>{const input={question:'API仕様を公式根拠で検証する。その後、互換性を維持して段階移行する。最後にテストする。成功条件はRollback可能であること。'},first=await engine.process(input,tenant),expected=JSON.stringify({task_graph:first.result.analysis_task_packet,five:first.result.five_stage,comparison:first.result.comparison,judgment:first.result.judgment,material:first.material});assert.equal((first.result.five_stage.execution.timings||[]).some((timing)=>Object.hasOwn(timing,'duration_ms')),false);assert.equal((first.runtime.parallel_execution.timings||[]).some((timing)=>Object.hasOwn(timing,'duration_ms')),true);for(let index=0;index<5;index+=1){const next=await engine.process(input,tenant);assert.equal(JSON.stringify({task_graph:next.result.analysis_task_packet,five:next.result.five_stage,comparison:next.result.comparison,judgment:next.result.judgment,material:next.material}),expected);}});});

test('visible English output keeps fixed Main8 with Evidence Status without derivation envelope in material.text',async()=>{await withEngine(async(engine)=>{const out=await engine.process({question:'Compare two API migration options. Success means compatibility and rollback.',language:'en'},tenant);assert.equal(out.result.judgment.output_language,'en');assert.equal(out.result.judgment['01_purpose'].label,'01 True Objective');assert.equal(out.result.judgment['07_evidence_status'].label,'07 Evidence Status');assertMaterialTextOmitsFixedEnvelope(out.material.text);assert.ok(out.result.judgment['07_evidence_status'].decision_basis.rule_ids.length>=1);assert.equal(out.result.comparison.selected_candidate,null);assert.deepEqual(out.result.comparison.candidate_ranking,[]);assert.match(out.material.text,/(?:Astera自身は.*(?:Recommendation|recommend).*行わない|Astera.*does not.*recommend)/i);});});
