'use strict';

const {BOUNDARY_CONNECTORS,createFragmentId,normalizeText,deepFreeze}=require('./core');

function splitWithIndex(text,regex){const output=[];let cursor=0;for(const match of text.matchAll(regex)){const index=match.index??0;if(index>cursor)output.push({text:text.slice(cursor,index),start:cursor,end:index});cursor=index+match[0].length;}if(cursor<text.length)output.push({text:text.slice(cursor),start:cursor,end:text.length});return output;}
function isolateFences(text){const fence=/```[\s\S]*?```|~~~[\s\S]*?~~~/gu,output=[];let cursor=0;for(const match of text.matchAll(fence)){const start=match.index??0;if(start>cursor)output.push({text:text.slice(cursor,start),start:cursor,end:start,fenced:false});output.push({text:match[0],start,end:start+match[0].length,fenced:true});cursor=start+match[0].length;}if(cursor<text.length)output.push({text:text.slice(cursor),start:cursor,end:text.length,fenced:false});return output;}
function isIdentifierDot(text,index){const before=text[index-1]??'',after=text[index+1]??'';return/[A-Za-z0-9_]/u.test(before)&&/[A-Za-z0-9_]/u.test(after);}
function splitSentences(text,base){const output=[];let start=0,quoteDepth=0,asciiQuoted=false;for(let index=0;index<text.length;index+=1){const ch=text[index];if(ch==='"'){asciiQuoted=!asciiQuoted;}else if(['「','『','“'].includes(ch)){quoteDepth+=1;}else if(['」','』','”'].includes(ch)){quoteDepth=Math.max(0,quoteDepth-1);}const boundary='。!?！？'.includes(ch)||(ch==='.'&&!isIdentifierDot(text,index));if(boundary&&quoteDepth===0&&!asciiQuoted){output.push({text:text.slice(start,index+1),start:base+start,end:base+index+1});start=index+1;}}if(start<text.length)output.push({text:text.slice(start),start:base+start,end:base+text.length});return output;}
function splitConnectors(segment){const regex=new RegExp(`(^|[、,]\\s*)(${BOUNDARY_CONNECTORS.join('|')})(?=\\s|、|,|[^ぁ-んァ-ヶ一-龠A-Za-z0-9_]|$)`,'gu'),matches=[...segment.text.matchAll(regex)];if(matches.length===0)return[segment];const output=[];let cursor=0;for(const match of matches){const splitAt=(match.index??0)+match[1].length;if(splitAt>cursor)output.push({...segment,text:segment.text.slice(cursor,splitAt),start:segment.start+cursor,end:segment.start+splitAt});cursor=splitAt;}if(cursor<segment.text.length)output.push({...segment,text:segment.text.slice(cursor),start:segment.start+cursor,end:segment.end});return output;}
function splitBullets(segment){const lines=segment.text.split('\n'),output=[];let offset=0;for(const line of lines){const clean=line.replace(/^\s*(?:[・*\-]|\d+[.)])\s*/u,'');const prefixLength=line.length-clean.length;if(clean.trim())output.push({...segment,text:clean,start:segment.start+offset+prefixLength,end:segment.start+offset+line.length});offset+=line.length+1;}return output;}
function quotationRole(text){if(/[『「“"][^』」”"]+[』」”"]/u.test(text))return['QUOTED'];return['DIRECT'];}
function contentRole(fenced){return fenced?['CODE_OR_QUOTED_BLOCK']:['NATURAL_LANGUAGE'];}

function fragmentInput({inputDocumentId,text,sourceAxes={},maxFragments=256}){
  const raw=String(text??''),normalized=normalizeText(raw),fileParts=splitWithIndex(normalized,/---FILE---/gu),fragments=[];let index=0;
  for(const filePart of fileParts){for(const fence of isolateFences(filePart.text)){const fenced={...fence,start:filePart.start+fence.start,end:filePart.start+fence.end};if(fenced.fenced){const fragmentText=normalizeText(fenced.text);if(!fragmentText)continue;const position=`${fenced.start}:${fenced.end}`;fragments.push({fragment_id:createFragmentId({inputDocumentId,canonicalSourcePosition:position,normalizedFragment:fragmentText}),input_document_id:inputDocumentId,text:fenced.text,normalized_fragment:fragmentText,canonical_source_position:position,span:{start:fenced.start,end:fenced.end},source_axes:{container_role:['FENCED_CONTAINER'],content_role:contentRole(true),quotation_role:['DIRECT'],...sourceAxes}});index+=1;if(index>=maxFragments)return deepFreeze({fragments,resource_limited:true,diagnostics:['MAX_FRAGMENTS_EXCEEDED']});continue;}
      for(const bullet of splitBullets(fenced)){for(const sentence of splitSentences(bullet.text,bullet.start)){for(const connector of splitConnectors(sentence)){const fragmentText=normalizeText(connector.text);if(!fragmentText)continue;const position=`${connector.start}:${connector.end}`;fragments.push({fragment_id:createFragmentId({inputDocumentId,canonicalSourcePosition:position,normalizedFragment:fragmentText}),input_document_id:inputDocumentId,text:connector.text,normalized_fragment:fragmentText,canonical_source_position:position,span:{start:connector.start,end:connector.end},source_axes:{container_role:['PLAIN_CONTAINER'],content_role:contentRole(false),quotation_role:quotationRole(fragmentText),...sourceAxes}});index+=1;if(index>=maxFragments)return deepFreeze({fragments,resource_limited:true,diagnostics:['MAX_FRAGMENTS_EXCEEDED']});}}}}
    }
  return deepFreeze({fragments,resource_limited:false,diagnostics:[]});
}

module.exports={fragmentInput};
