'use strict';

const {ClaimStatus,UndeterminedReason}=require('./confirmation');
const {deepFreeze}=require('./core');

function resultMap(results){return new Map(results.map((result)=>[result.claim_id,result]));}
function domainArray(domain,names){for(const name of names)if(Array.isArray(domain?.primary?.[name]))return domain.primary[name];return[];}
function factLane(claims,results){const byId=resultMap(results),confirmedClaims=claims.filter((claim)=>byId.get(claim.claim_id)?.status===ClaimStatus.CONFIRMED),undeterminedClaims=claims.filter((claim)=>byId.get(claim.claim_id)?.status===ClaimStatus.UNDETERMINED);return deepFreeze({lane:'fact',confirmed_claim_ids:confirmedClaims.map((claim)=>claim.claim_id).sort(),undetermined_claim_ids:undeterminedClaims.map((claim)=>claim.claim_id).sort(),confirmed:confirmedClaims.map((claim)=>({claim_id:claim.claim_id,text:claim.raw_text,status:ClaimStatus.CONFIRMED,supported_scope:byId.get(claim.claim_id).supported_scope,bindings:byId.get(claim.claim_id).support_binding_ids||[]})),unconfirmed:undeterminedClaims.map((claim)=>({claim_id:claim.claim_id,text:claim.raw_text,status:ClaimStatus.UNDETERMINED,reasons:byId.get(claim.claim_id).reasons})),opinions:[],evidence_need:undeterminedClaims.map((claim)=>({item:claim.raw_text,reason:(byId.get(claim.claim_id).reasons||[]).join(' / ')})),evidence_gaps:undeterminedClaims.map((claim)=>({item:claim.raw_text,reason:(byId.get(claim.claim_id).reasons||[]).join(' / ')}))});}
function riskLane(claims,results,task,domain){const byId=resultMap(results),criticalIds=new Set((task.critical_target_ids||[]).map(String)),targets=claims.filter((claim)=>criticalIds.has(claim.claim_id)),riskLens=domainArray(domain,['risk_lens','risk_checks','risks','safety_checks']),hardBlockers=task.hard_blockers||[],riskItems=[...riskLens.map((item,index)=>({key:`domain-risk-${index+1}`,impact:String(item),weight:20,source:'DOMAIN_LENS'})),...hardBlockers.map((item,index)=>({key:`hard-blocker-${index+1}`,impact:String(item),weight:100,source:'TASK_GRAPH'}))];return deepFreeze({lane:'risk',source:'CANONICAL_RECORDS_PLUS_EXTERNAL_CRITICALITY',target_count:targets.length,confirmed_count:targets.filter((claim)=>byId.get(claim.claim_id)?.status===ClaimStatus.CONFIRMED).length,undetermined_count:targets.filter((claim)=>byId.get(claim.claim_id)?.status!==ClaimStatus.CONFIRMED).length,target_claim_ids:targets.map((claim)=>claim.claim_id).sort(),risk_count:riskItems.length,risks:riskItems,highest:riskItems.sort((a,b)=>b.weight-a.weight||a.key.localeCompare(b.key))[0]||null,hard_constraints:[...(task.constraints||[]),...(task.prohibitions||[]),...(task.preserve||[])],safety_gates:[...(task.prohibitions||[])],level:hardBlockers.length?'high':riskItems.length?'medium':'low'});}
function multiLane(claims,results,domain){const byId=resultMap(results),confirmed=claims.filter((claim)=>byId.get(claim.claim_id)?.status===ClaimStatus.CONFIRMED),lenses=domainArray(domain,['multi_lens','perspectives']);return deepFreeze({lane:'multi',supported_scopes:confirmed.map((claim)=>({claim_id:claim.claim_id,...byId.get(claim.claim_id).supported_scope})).sort((a,b)=>a.claim_id.localeCompare(b.claim_id)),perspectives:lenses.map((item,index)=>({id:`domain-perspective-${index+1}`,focus:String(item),source:'DOMAIN_LENS',claim_ids:confirmed.map((claim)=>claim.claim_id)})),trade_off_map:lenses.map((item,index)=>({id:`domain-perspective-${index+1}`,dimension:String(item),status:'MATERIAL_ONLY'}))});}
function inquiryLane(claims,results,domain){const byId=resultMap(results),open=claims.filter((claim)=>byId.get(claim.claim_id)?.status===ClaimStatus.UNDETERMINED).map((claim)=>({claim_id:claim.claim_id,reasons:byId.get(claim.claim_id).reasons,missing_scope_fields:byId.get(claim.claim_id).gate_details?.missing_scope_fields||[]})).sort((a,b)=>a.claim_id.localeCompare(b.claim_id)),evidenceNeeds=domainArray(domain,['evidence_to_collect','required_evidence']);return deepFreeze({lane:'inquiry',problem_health:{healthy:open.length===0,reason:open.length?'Canonical Claims remain UNDETERMINED.':'Canonical Claims are traceable.'},open_items:open,missing_fields:[...new Set(open.flatMap((item)=>item.missing_scope_fields.map((field)=>`${item.claim_id}:${field}`)))].sort(),missing_questions:[...new Set([...open.flatMap((item)=>item.reasons),...evidenceNeeds])].sort()});}
function compareLane(claims,results,policyByClaimId,domain){const byId=resultMap(results);let numerator=0,denominator=0;const booleans=[];for(const claim of claims){const policy=policyByClaimId[claim.claim_id]||policyByClaimId.get?.(claim.claim_id),required=policy?.required_scope_fields||[],confirmed=byId.get(claim.claim_id)?.status===ClaimStatus.CONFIRMED,known=required.filter((field)=>claim[field]!=='UNKNOWN');denominator+=required.length;if(confirmed)numerator+=known.length;booleans.push({claim_id:claim.claim_id,required_scope_defined:required.length>0,all_required_scope_confirmed:confirmed&&known.length===required.length});}return deepFreeze({lane:'compare',material_only:true,counts:{claims:claims.length,confirmed:results.filter((result)=>result.status===ClaimStatus.CONFIRMED).length,undetermined:results.filter((result)=>result.status===ClaimStatus.UNDETERMINED).length,insufficient_evidence:results.filter((result)=>result.reasons.includes(UndeterminedReason.INSUFFICIENT_EVIDENCE)).length,conflicts:results.filter((result)=>result.reasons.includes(UndeterminedReason.CONFLICT)).length},coverage:denominator>0?{numerator,denominator,ratio:numerator/denominator}:null,scope_booleans:booleans,dimensions:domainArray(domain,['compare_lens','comparison_dimensions']).map(String),selected_candidate:null,candidate_ranking:[],rejected_candidates:[],verdict:{decision:'MATERIAL_ONLY',reason:'Astera does not select, rank, recommend, adopt, or reject candidates.'}});}
function buildFiveLanes({claims,results,policyByClaimId,task={},domain={}}){return deepFreeze({fact:factLane(claims,results),risk:riskLane(claims,results,task,domain),multi:multiLane(claims,results,domain),inquiry:inquiryLane(claims,results,domain),compare:compareLane(claims,results,policyByClaimId,domain)});}

module.exports={factLane,riskLane,multiLane,inquiryLane,compareLane,buildFiveLanes};
